### ISSUE TITLE
Set Azure AD Application - You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by kdharma** [LockTar/AzureAdApplicationManagement#35]
Hi there, I'm getting error when tyring out the Set Azure AD Application task. I already set all the required parameters and when I run it, I'm getting below error [You cannot call a method on a null-valued expression]

![image](https://user-images.githubusercontent.com/30489602/70033797-c596ad80-15e2-11ea-9e6e-ab969c6399c8.png)

Is there a way to have a more detailed log to fix this issue?

**Comment by LockTar** [comment]
> Is there a way to have a more detailed log to fix this issue?

Have you set the variable `System.Debug` to `true`?

**Comment by LockTar** [comment]
Because the extension has very detailed logging if you enable that above. In your screenshot I only see the information messages.

**Comment by kdharma** [comment]
Hi @LockTar here is the detailed logging. It seems to be failing when its trying to set owners. I already try to use email address or my account object id as the value of the owners and also try to set it as empty. All return below errors.

![image](https://user-images.githubusercontent.com/30489602/70120561-78c4dc80-169f-11ea-82c0-6064d837608f.png)
019-12-04T07:03:06.5658393Z ##[debug]Set owners of the application. Current owners are:
2019-12-04T07:03:06.6970927Z ##[debug]Check if owner is an Object Id or UserPrincipalName
2019-12-04T07:03:06.7152468Z ##[debug]Owner is an Object Id so add it to the list as desired owners
2019-12-04T07:03:06.7171492Z ##[debug]Check if owner is an Object Id or UserPrincipalName
2019-12-04T07:03:06.7188874Z ##[debug]Owner is an Object Id so add it to the list as desired owners
2019-12-04T07:03:06.7418262Z ##[debug]Caught exception from task script.
2019-12-04T07:03:06.7447819Z ##[debug]Error record:
2019-12-04T07:03:06.7893958Z ##[debug]Set-AadApplication : You cannot call a method on a null-valued expression.
2019-12-04T07:03:06.7906185Z ##[debug]At D:\a\_tasks\Set-Azure-AD-Application_dce5b732-75fe-5bd8-8edc-eb8b27a0944a\2.0.22\Main.ps1:118 char:1
2019-12-04T07:03:06.7918056Z ##[debug]+ Set-AadApplication `
2019-12-04T07:03:06.7930366Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~
2019-12-04T07:03:06.7942723Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Set-AadApplication], RuntimeException
2019-12-04T07:03:06.7955711Z ##[debug]    + FullyQualifiedErrorId : InvokeMethodOnNull,Set-AadApplication
2019-12-04T07:03:06.7968046Z ##[debug] 
2019-12-04T07:03:06.7986073Z ##[debug]Script stack trace:
2019-12-04T07:03:06.8025160Z ##[debug]at Set-AadApplication, D:\a\_tasks\Set-Azure-AD-Application_dce5b732-75fe-5bd8-8edc-eb8b27a0944a\2.0.22\scripts\Set-AadApplication.psm1: line 134
2019-12-04T07:03:06.8036467Z ##[debug]at <ScriptBlock>, D:\a\_tasks\Set-Azure-AD-Application_dce5b732-75fe-5bd8-8edc-eb8b27a0944a\2.0.22\Main.ps1: line 118
2019-12-04T07:03:06.8049387Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-04T07:03:06.8062171Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-12-04T07:03:06.8075504Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-12-04T07:03:06.8086425Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-04T07:03:06.8106080Z ##[debug]Exception:
2019-12-04T07:03:06.8149890Z ##[debug]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
2019-12-04T07:03:06.8161934Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-12-04T07:03:06.8175994Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-12-04T07:03:06.8187312Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-04T07:03:06.8198376Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-04T07:03:06.8209859Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-12-04T07:03:06.8221104Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-12-04T07:03:06.8232895Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2019-12-04T07:03:06.8244066Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2019-12-04T07:03:06.8256134Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2019-12-04T07:03:06.8463072Z ##[error]You cannot call a method on a null-valued expression.
2019-12-04T07:03:06.8469964Z ##[debug]Processed: ##vso[task.logissue type=error]You cannot call a method on a null-valued expression.
2019-12-04T07:03:06.8483331Z ##[debug]Processed: ##vso[task.complete result=Failed]

**Comment by kdharma** [comment]
Hi @LockTar would it be possible the cause of this issue is because the application that gets created doesn't have any owners yet? 
When I look at the log the issues were raised from line 134, which is trying to validate whether current owner is already exists within the owner list. Since the current owner is empty, the statement `$($currentOwners.ObjectId).Contains($owner)` will failed.

![image](https://user-images.githubusercontent.com/30489602/70123488-6188ed80-16a5-11ea-8507-58f112cf2687.png)

**Comment by LockTar** [comment]
> Hi @LockTar would it be possible the cause of this issue is because the application that gets created doesn't have any owners yet?

I think your right. I added an extra check. Extension should be updated already:
https://github.com/LockTar/AzureAdApplicationManagement/blob/56810847e34a8a3a1295ba646d828d7de4e482a0/scripts/Set-AzureAdApplication/v2/Set-AadApplication.psm1#L112-L115

Can you check if this works for you?

**Comment by kdharma** [comment]
Still failing error thrown move to line 138
![image](https://user-images.githubusercontent.com/30489602/70192933-f59f9700-172f-11ea-91d2-2da3b0c00578.png)

**Comment by LockTar** [comment]
Changed the check to:

https://github.com/LockTar/AzureAdApplicationManagement/blob/master/scripts/Set-AzureAdApplication/v2/Set-AadApplication.psm1#L134

and 

https://github.com/LockTar/AzureAdApplicationManagement/blob/master/scripts/Set-AzureAdApplication/v2/Set-AadApplication.psm1#L144-L156

**Comment by kdharma** [comment]
Thank you @LockTar that fixed the problem.
